vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /uploads/lieux
            upload_destination: '%kernel.project_dir%/public/uploads/lieux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer